"""
pages/privacy.py
Privacy policy page — accessible from the app footer.
Streamlit multi-page apps automatically create navigation for files in /pages.
"""
import streamlit as st

st.set_page_config(page_title="Privacy Policy · PawMatch", page_icon="🐾")

st.title("🐾 PawMatch — Privacy Policy")
st.caption("Last updated: May 2026")

st.markdown("""
### What PawMatch collects

When you use PawMatch, you type a lifestyle description into a text box.
That text is sent to OpenAI's API to generate a pet recommendation.
**We do not store your queries.** They exist only for the duration of your
browser session and are discarded when you close the tab.

Pets you star or save exist only in your browser's session memory.
They are never sent to a server or stored in a database.

### Third-party services

PawMatch uses the following third-party services:

- **OpenAI API** — your lifestyle query and retrieved pet profiles are sent
  to OpenAI to generate a recommendation. OpenAI's privacy policy applies:
  https://openai.com/policies/privacy-policy
- **RescueGroups.org API** — pet listings are fetched from RescueGroups.org
  and indexed locally. No user data is sent to RescueGroups.
- **Zippopotam.us** — if you enter a custom ZIP code, it is sent to
  Zippopotam.us to look up coordinates. No other data is sent.

### Pet data

Animal listings displayed in PawMatch come from RescueGroups.org and are
the property of the individual shelters and rescue organisations that listed
them. PawMatch displays this data with attribution and links back to the
original listing where available.

Pet availability changes daily. PawMatch is not responsible for the accuracy
of individual listings — always contact the shelter directly to confirm a pet
is still available before visiting.

### No advertising

PawMatch contains no advertising and does not sell or share any data with
advertisers or data brokers.

### No user accounts

PawMatch does not offer user accounts. No name, email address, or personal
information is collected at any point.

### AI-generated content

Pet recommendations are generated by an AI model (OpenAI GPT-4o-mini).
They are suggestions only and should not be treated as professional advice.
Always visit the shelter and meet a pet in person before adopting.

### Contact

This is a non-commercial portfolio project. For questions or concerns,
please open an issue on the
[GitHub repository](https://github.com/jkm1274/rag-pet-matchmaker).
""")

st.divider()
st.caption("← Return to the main app using the sidebar navigation.")